//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler_NEA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler_NEA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_gracefully_aging_tabby_cat__its_fur_a_mix_of_sil_by_b0dean_dima0iy {
            get {
                object obj = ResourceManager.GetObject("a_gracefully_aging_tabby_cat__its_fur_a_mix_of_sil_by_b0dean_dima0iy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_gracefully_blooming_cherry_blossom__delicate_pet_by_b0dean_dijtlr9 {
            get {
                object obj = ResourceManager.GetObject("a_gracefully_blooming_cherry_blossom__delicate_pet_by_b0dean_dijtlr9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_single_rocket_in_the_middle_of_the_standing_stil_by_b0dean_dijtih4 {
            get {
                object obj = ResourceManager.GetObject("a_single_rocket_in_the_middle_of_the_standing_stil_by_b0dean_dijtih4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_sunflower__by_b0dean_dim9zbo {
            get {
                object obj = ResourceManager.GetObject("a_sunflower__by_b0dean_dim9zbo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlbedoBase_XL_A_mesmerizing_abstract_composition_featuring_a_v_0 {
            get {
                object obj = ResourceManager.GetObject("AlbedoBase_XL_A_mesmerizing_abstract_composition_featuring_a_v_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlbedoBase_XL_A_mesmerizing_abstract_composition_featuring_a_v_3 {
            get {
                object obj = ResourceManager.GetObject("AlbedoBase_XL_A_mesmerizing_abstract_composition_featuring_a_v_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alchemyrefiner_alchemymagic_0_517da2d5_cfae_4e90_9585_75b059bfc509_0 {
            get {
                object obj = ResourceManager.GetObject("alchemyrefiner_alchemymagic_0_517da2d5-cfae-4e90-9585-75b059bfc509_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alchemyrefiner_alchemymagic_0_c8310571_54c2_4394_b763_b4352fa09e24_0 {
            get {
                object obj = ResourceManager.GetObject("alchemyrefiner_alchemymagic_0_c8310571-54c2-4394-b763-b4352fa09e24_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap one_dinosaur_in_the_centre_of_the_image_the_dinosa_by_b0dean_dim9yez {
            get {
                object obj = ResourceManager.GetObject("one_dinosaur_in_the_centre_of_the_image_the_dinosa_by_b0dean_dim9yez", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_960 {
            get {
                object obj = ResourceManager.GetObject("settings-960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
